---
- name: Get rule definition
  paloaltonetworks.panos.panos_security_rule_facts:
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"
    names: 
        - "Ansible Attacker Rule"
  register: ruleresults

- name: Remove Forwarding Rule
  paloaltonetworks.panos.panos_security_rule:
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"
    rule_name: "Ansible Attacker Rule"

- name: Remove Log Forwarding Profile Match List
  paloaltonetworks.panos.panos_log_forwarding_profile_match_list:
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"
    name: "QRadar Shadowman"
    log_forwarding_profile: 'QRadar Shadowman'
    state: absent

- name: Remove Log Forwarding Profile
  paloaltonetworks.panos.panos_log_forwarding_profile:
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"
    name: "QRadar Shadowman"
    state: absent

- name: Remove Syslog server Palo
  paloaltonetworks.panos.panos_syslog_server:
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"
    state: absent
    name: "QRadar Shadowman"
    syslog_profile: "QRadar Shadowman"
    server: "{{ hostvars['qradar.shadowman.dev']['ip_addr'] }}"

- name: Remove Syslog profile Palo
  paloaltonetworks.panos.panos_syslog_profile:
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"
    name: "QRadar Shadowman"
    state: absent

- name: Commit Changes
  paloaltonetworks.panos.panos_commit_firewall:
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"