---
# handlers file for snort-config
- name: restart snort
  ansible.builtin.service:
    name: snort
    state: restarted

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
