---
- name: Delete Rule
  paloaltonetworks.panos.panos_security_rule:
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"
    rule_name: "{{ rule_name }}"
    state: "{{ state }}"

- name: Commit Changes
  paloaltonetworks.panos.panos_commit_firewall:
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"