---
- name: Remove Palo for external logging
  hosts: localhost
  gather_facts: false

  roles:
    - remove_log_forwarding_palo

- name: Remove Palo log source from QRadar
  hosts: qradar.shadowman.dev
  gather_facts: false
  become: false

  roles:
    - disable_log_forwarding_palo
