---
- name: Configure Palo for external logging
  hosts: localhost
  gather_facts: false

  roles:
    - set_log_forwarding_palo

- name: Add Palo log source to QRadar
  hosts: qradar.shadowman.dev
  gather_facts: false
  become: false

  roles:
    - enable_log_forwarding_palo
