---
- name: Verify Snort rules
  hosts: snort.shadowman.dev
  gather_facts: false

  vars:
    ids_provider: snort

  tasks:
    - name: import ids_rule_facts
      ansible.builtin.import_role:
        name: ids_rule_facts

    - name: output rules facts
      debug:
        var: ansible_facts.ids_rules
