---
- name: Verify Snort rules
  hosts: snort.shadowman.dev
  gather_facts: false

  vars:
    ids_provider: snort

  tasks:
    - name: Import ids_rule_facts
      ansible.builtin.import_role:
        name: ids_rule_facts

    - name: Output rules facts
      ansible.builtin.debug:
        var: ansible_facts.ids_rules
