---
- name: Add Snort rule
  hosts: snort.shadowman.dev
  gather_facts: false

  vars:
    ids_provider: snort

  tasks:
    - name: Add snort web attack rule
      ansible.builtin.include_role:
        name: ids_rule
      vars:
        ids_rules_file: /etc/snort/rules/local.rules
        ids_rule_state: present
