---
- name: "Add gw route on attacker node {{ inventory_hostname }}"
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/network-scripts/route-ens3
    line: "{{ hostvars[inventory_hostname | regex_replace('attacker.shadowman.dev', 'palo.shadowman.dev')]['ip_addr'] }} dev ens3"
    create: true
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart-network

- name: "Add snort route on attacker node {{ inventory_hostname }}"
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/network-scripts/route-ens3
    line: "{{ hostvars[inventory_hostname | regex_replace('attacker.shadowman.dev', 'snort.shadowman.dev')]['ip_addr'] }} via {{ hostvars[inventory_hostname | regex_replace('attacker.shadowman.dev', 'palo.shadowman.dev')]['ip_addr'] }} dev ens3 metric 5"
    create: true
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart-network
