---
- name: Host routes from attacker
  ansible.builtin.include_tasks: add_hostroutes_from_attacker_to_checkpoint.yml
  when: '"attack" in inventory_hostname'

- name: Host routes from snort
  ansible.builtin.include_tasks: add_hostroutes_from_snort_to_checkpoint.yml
  when: '"snort" in inventory_hostname'
