---
- name: Find snort rules
  ansible.builtin.find:
    paths: "{{ ids_config_snort_rules_dir }}"
    patterns: "*.rules"
    recurse: true
  register: ids_config_snort_rules_files

- name: Apply config template for snort provider
  ansible.builtin.template:
    src: snort.conf.j2
    dest: /etc/snort/snort.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart snort

- name: Enable remote logging
  when: (ids_config_remote_log is defined) and ids_config_remote_log
  block:
    - name: Apply rsyslog config
      ansible.builtin.template:
        src: ids_confg_snort_rsyslog.conf.j2
        dest: /etc/rsyslog.d/ids_confg_snort_rsyslog.conf
        backup: true
        owner: root
        group: root
        mode: "0644"
      notify:
        - Restart rsyslog

- name: Disable remote logging
  when: (ids_config_remote_log is defined) and not ids_config_remote_log
  block:
    - name: Check for rsyslog config
      ansible.builtin.stat:
        path: /etc/rsyslog.d/ids_confg_snort_rsyslog.conf
      register: st

    - name: Backup rsyslog config
      ansible.builtin.copy:
        src: /etc/rsyslog.d/ids_confg_snort_rsyslog.conf
        dest: /etc/rsyslog.d/ids_confg_snort_rsyslog.conf.backup
        remote_src: true
        backup: true
        owner: root
        group: root
        mode: "0644"
      when: st.stat.exists

    - name: Remove ids_config_snort_rsyslog.conf rsyslog config
      ansible.builtin.file:
        path: /etc/rsyslog.d/ids_confg_snort_rsyslog.conf
        state: absent
      when: st.stat.exists
      notify:
        - Restart rsyslog
