---
- name: Create Rule
  paloaltonetworks.panos.panos_security_rule:
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"
    rule_name: "{{ rule_name }}"
    description: "{{ description }}"
    source_zone: "{{ source_zone }}"
    destination_zone: "{{ destination_zone }}"
    source_ip: "{{ source_ip }}"
    source_user: "{{ source_user }}"
    destination_ip: "{{ destination_ip }}"
    category: "{{ category }}"
    application: "{{ application }}"
    service: "{{ service }}"
    hip_profiles: "{{ hip_profiles }}"
    action: "{{ actiontaken }}"
    log_setting: "{{ logsetting | default(omit) }}"
    state: "{{ state }}"

- name: Commit Changes
  paloaltonetworks.panos.panos_commit_firewall:
    provider:
      ip_address: "{{ palo_ip_address }}"
      username: "{{ palo_username }}"
      password: "{{ palo_password }}"