---
- name: Add remote logging to QRadar
  ibm.qradar.qradar_log_source_management:
    name: "Snort rsyslog source - {{ hostvars['snort.shadowman.dev']['ip_addr'] }}"
    type_name: "Snort Open Source IDS"
    state: present
    description: "Snort rsyslog source"
    identifier: "{{ hostvars['snort.shadowman.dev']['inventory_hostname'] }}"

- name: deploy the new log source
  ibm.qradar.qradar_deploy:
    type: INCREMENTAL
  failed_when: false