---
- name: Block for cert Check
  block:

    - name: Get the cert from a port
      community.crypto.get_certificate:
        host: "{{ inventory_hostname }}"
        port: "{{ certificate_port }}"
      delegate_to: localhost
      register: cert

    - name: Set facts for report
      ansible.builtin.set_fact:
        expire_days: "{{ ((cert.not_after | to_datetime('%Y%m%d%H%M%SZ')) - (ansible_date_time.iso8601 | to_datetime('%Y-%m-%dT%H:%M:%SZ'))).days }}"
        issuer: "{{ cert.issuer }}"
        expiration: "{{ cert.not_after | to_datetime('%Y%m%d%H%M%SZ') }}"
        expired: "{{ cert.expired }}"

  rescue:

    - name: Display error
      ansible.builtin.debug:
        msg: "{{ cert.msg }}"
